# Generated by Django 3.1.4 on 2021-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
