# Generated by Django 3.1.4 on 2021-01-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_review_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='Marian', max_length=40),
        ),
    ]
